/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponInfoReceiveInfo 优惠券失效信息
type CouponInfoReceiveInfo struct {
	// 优惠券领用结束时间
	EndTime string `json:"end_time"`
	// 是否限制一人使用
	LimitNumOnePerson int64 `json:"limit_num_one_person"`
	// 优惠券领用开始时间
	StartTime string `json:"start_time"`
	// 优惠券领用总数
	TotalNum int64 `json:"total_num"`
}
