/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject6 struct for InlineObject6
type InlineObject6 struct {
	// 小商店内部商品ID，与out_product_id二选一
	ProductId int64 `json:"product_id,omitempty"`
	// 商家自定义商品ID，与product_id二选一
	OutProductId string `json:"out_product_id,omitempty"`
	// 默认0:获取线上数据, 1:获取草稿数据
	NeedEditSpu int32 `json:"need_edit_spu,omitempty"`
}
