/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// StockUpdateRspData struct for StockUpdateRspData
type StockUpdateRspData struct {
	UpdateTime string `json:"update_time,omitempty"`
}
