/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SkuBatchAddReq 
type SkuBatchAddReq struct {
	Skus []Sku `json:"skus,omitempty"`
}
