/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// Spu 
type Spu struct {
	// 标题
	Title string `json:"title,omitempty"`
	// 副标题
	SubTitle string `json:"sub_title,omitempty"`
	// 主图,多张,列表
	HeadImg []string `json:"head_img,omitempty"`
	DescInfo SpuDescInfo `json:"desc_info,omitempty"`
	// 商家自定义商品ID
	OutProductId string `json:"out_product_id,omitempty"`
	// 小商店内部商品ID
	ProductId int64 `json:"product_id,omitempty"`
	// 商家需要申请品牌
	BrandId int64 `json:"brand_id,omitempty"`
	// 商品线上状态;初始值-0;上架-5;回收站-6;逻辑删除-9;自主下架-11;售磬下架-12;违规下架/风控系统下架-13
	Status int64 `json:"status,omitempty"`
	// 商品草稿状态;初始值-0;编辑中-1;审核中-2;审核失败-3;审核成功-4
	EditStatus int64 `json:"edit_status,omitempty"`
	// 商品SKU最小价格（单位：分）
	MinPrice int64 `json:"min_price,omitempty"`
	// 类目
	Cats []Cats `json:"cats,omitempty"`
	// 属性
	Attrs []Attrs `json:"attrs,omitempty"`
	// 商品型号
	Model string `json:"model,omitempty"`
	// 该 skus 列表非必填，可另行通过 BatchAddSKU 添加 SKU
	Shopcat []SpuShopcat `json:"shopcat,omitempty"`
	// 该 skus 列表非必填，可另行通过 BatchAddSKU 添加 SKU
	Skus []SpuSkus `json:"skus,omitempty"`
}
