/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject23 struct for InlineObject23
type InlineObject23 struct {
	// 用户openid
	Openid string `json:"openid"`
	// 优惠券ID，可从获取优惠券中获得
	CouponId int64 `json:"coupon_id"`
}
