/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// BusiLicense 营业执照/登记证书信息
type BusiLicense struct {
	// 营业执照类型 1-三证合一 2-普通营业执照
	LicenseType int64 `json:"license_type"`
	PicFile PicFile `json:"pic_file"`
	// 请填写营业执照上的注册号/统一社会信用代码，须为15位数字或18位数字大写字母。示例值;123456789012345678 特殊规则;长度最小15个字节
	RegistrationNum string `json:"registration_num"`
	// 1、请填写营业执照/登记证书的商家名称，2~110个字符，支持括号 2、个体工商户/党政、机关及事业单位，不能以“公司”结尾。 3、个体工商户，若营业执照上商户名称为空或为“无”，请填写\"个体户+经营者姓名\"，如“个体户张三” 。示例值-腾讯科技有限公司
	MerchantName string `json:"merchant_name"`
	// 请填写证件的经营者/法定代表人姓名。示例值-张三
	LegalRepresentative string `json:"legal_representative"`
	// 注册地址
	RegisteredAddrs string `json:"registered_addrs,omitempty"`
	// 注册日期，格式2014-01-01
	StartDate string `json:"start_date"`
	// 结束有效期，格式;2014-01-01;1、若证件有效期为长期，请填写;长期。2、结束时间需大于开始时间。3、有效期必须大于60天，即结束时间距当前时间需超过60天。
	EndDate string `json:"end_date"`
}
