/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject4 struct for InlineObject4
type InlineObject4 struct {
	FCatId int64 `json:"f_cat_id"`
}
