/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// PayInfo 
type PayInfo struct {
	// 支付方式（目前只有\"微信支付\"）
	PayMethod string `json:"pay_method,omitempty"`
	// 预支付ID
	PrepayId string `json:"prepay_id,omitempty"`
	// 支付订单号
	TransactionId string `json:"transaction_id,omitempty"`
	// 预付款时间
	PrepayTime string `json:"prepay_time,omitempty"`
	// 付款时间
	PayTime string `json:"pay_time,omitempty"`
}
