/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SkuUpdateRspData struct for SkuUpdateRspData
type SkuUpdateRspData struct {
	SkuId int64 `json:"sku_id,omitempty"`
	UpdateTime string `json:"update_time,omitempty"`
}
