/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// IdCardInfo 身份证
type IdCardInfo struct {
	PortraitPicFile PicFile `json:"portrait_pic_file"`
	NationPicFile PicFile `json:"nation_pic_file"`
	// 请填写经营者/法定代表人对应身份证的姓名，2~30个中文字符、英文字符、符号。
	IdCardName string `json:"id_card_name"`
	// 请填写经营者/法定代表人对应身份证的号码
	IdCardNumber string `json:"id_card_number"`
	// 注册日期，格式：2014-01-01
	StartDate string `json:"start_date"`
	// 结束有效期，格式：2014-01-01;1、若证件有效期为长期，请填写：长期。2、结束时间需大于开始时间。3、有效期必须大于60天，即结束时间距当前时间需超过60天。
	EndDate string `json:"end_date"`
}
