/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// BrandRspBrandInfo struct for BrandRspBrandInfo
type BrandRspBrandInfo struct {
	// 品牌ID
	BrandId int64 `json:"brand_id,omitempty"`
	// 品牌名称
	BrandName string `json:"brand_name,omitempty"`
}
