/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SpuShopcat struct for SpuShopcat
type SpuShopcat struct {
	// 分类ID，对应信息通过 get_shop_cat 接口拿到
	ShopcatId int64 `json:"shopcat_id,omitempty"`
}
