/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject15 struct for InlineObject15
type InlineObject15 struct {
	// 小商店内部商品ID，与out_product_id二选一
	ProductId int64 `json:"product_id,omitempty"`
	// 商家自定义商品ID，与product_id二选一
	OutProductId string `json:"out_product_id,omitempty"`
	// out_sku_id、sku_id 二选一
	SkuId int64 `json:"sku_id,omitempty"`
	// out_sku_id、sku_id二选一
	OutSkuId string `json:"out_sku_id,omitempty"`
	// 1:全量更新 2:增量更新
	Type int32 `json:"type"`
	// 全量更新时，stock_num必须大于0；增量更新时正数增加库存，负数减库存
	StockNum int64 `json:"stock_num"`
}
