/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// Attrs 属性
type Attrs struct {
	// 属性键key（属性自定义用）
	AttrKey string `json:"attr_key"`
	// 属性值（属性自定义用）
	AttrValue string `json:"attr_value"`
}
