/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// DeliveryGetFreightTemplateRsp 
type DeliveryGetFreightTemplateRsp struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	TemplateList []FreightTemplateRsp `json:"template_list,omitempty"`
}
