/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	Appid string `json:"appid"`
	// 主体类型,\"4\"-个体工商户，营业执照上的主体类型一般为个体户、个体工商户、个体经营。\"2\"-企业，营业执照上的主体类型一般为有限公司、有限责任公司。
	SubjectType string `json:"subject_type"`
	BusiLicense BusiLicense `json:"busi_license"`
	OrganizationCodeInfo OrganizationCodeInfo `json:"organization_code_info,omitempty"`
	IdCardInfo IdCardInfo `json:"id_card_info"`
	SuperAdministratorInfo SuperAdministratorInfo `json:"super_administrator_info"`
	// 商户简称 UTF-8格式，中文占3个字节，即最多16个汉字长度。将在支付完成页向买家展示，需与商家的实际售卖商品相符 。示例值：腾讯
	MerchantShortname string `json:"merchant_shortname"`
	// 特殊资质 1、根据商户经营业务要求提供相关资质，详情查看《行业对应特殊资质》。2、请提供为“申请商家主体”所属的特殊资质，可授权使用总公司/分公司的特殊资 质；3、最多可上传5张照片，请填写通过图片上传接口预先上传图片生成好的MediaID 。
	SpecialQualification []SuperAdministratorInfo `json:"special_qualification,omitempty"`
	// 补充材料
	SupplementaryMaterial []SuperAdministratorInfo `json:"supplementary_material,omitempty"`
	// 补充描述
	SupplementaryDesc string `json:"supplementary_desc,omitempty"`
}
