/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// ReturnInfo 
type ReturnInfo struct {
	AddressInfo AddressInfo `json:"address_info"`
	// 邮箱
	Mail string `json:"mail"`
	CompanyAddress AddressInfo `json:"company_address"`
}
