/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// PproductInfo 
type PproductInfo struct {
	// 小商店内部商品ID
	ProductId int64 `json:"product_id,omitempty"`
	// 小商店内部skuID
	SkuId int64 `json:"sku_id,omitempty"`
	// sku数量
	SkuCnt int64 `json:"sku_cnt,omitempty"`
	// 正在售后/退款流程中的sku数量
	OnAftersaleSkuCnt int64 `json:"on_aftersale_sku_cnt,omitempty"`
	// 完成售后/退款的sku数量
	FinishAftersaleSkuCnt int64 `json:"finish_aftersale_sku_cnt,omitempty"`
	// 标题
	Title string `json:"title,omitempty"`
	// sku小图
	ThumbImg string `json:"thumb_img,omitempty"`
	// 售卖价格,以分为单位
	SlaePrice int64 `json:"slae_price,omitempty"`
	SkuAttrs []Attrs `json:"sku_attrs,omitempty"`
}
