/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SpuUpdateRspData struct for SpuUpdateRspData
type SpuUpdateRspData struct {
	ProductId int64 `json:"product_id,omitempty"`
	OutProductId string `json:"out_product_id,omitempty"`
	UpdateTime string `json:"update_time,omitempty"`
}
