/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// DeliveryGetCompanyListRspDataCompanyList struct for DeliveryGetCompanyListRspDataCompanyList
type DeliveryGetCompanyListRspDataCompanyList struct {
	// 快递公司id
	DeliveryId string `json:"delivery_id,omitempty"`
	// 快递公司名称
	DeliveryName string `json:"delivery_name,omitempty"`
}
