/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject14 struct for InlineObject14
type InlineObject14 struct {
	// 小商店内部商品ID，与out_product_id二选一
	ProductId int64 `json:"product_id,omitempty"`
	// 商家自定义商品ID，与product_id二选一
	OutProductId string `json:"out_product_id,omitempty"`
	// out_sku_id、sku_id 二选一
	SkuId int64 `json:"sku_id,omitempty"`
	// out_sku_id、sku_id二选一
	OutSkuId string `json:"out_sku_id,omitempty"`
	// 售卖价格,以分为单位
	SalePrice int64 `json:"sale_price"`
	// 市场价格,以分为单位
	MarketPrice int64 `json:"market_price"`
}
