/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponStockInfo struct for CouponStockInfo
type CouponStockInfo struct {
	// 优惠券发放量
	IssuedNum int64 `json:"issued_num,omitempty"`
	// 优惠券领用量
	ReceiveNum int64 `json:"receive_num,omitempty"`
	// 优惠券已用量
	UsedNum int64 `json:"used_num,omitempty"`
}
