/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// DeliveryGetCompanyListRspData struct for DeliveryGetCompanyListRspData
type DeliveryGetCompanyListRspData struct {
	CompanyList []DeliveryGetCompanyListRspDataCompanyList `json:"company_list,omitempty"`
}
