/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// OrderExtInfo struct for OrderExtInfo
type OrderExtInfo struct {
	// 用户备注
	CustomerNotes string `json:"customer_notes,omitempty"`
	// 商家备注
	MerchantNotes string `json:"merchant_notes,omitempty"`
}
