/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// Coupon 
type Coupon struct {
	// 优惠券
	CouponId int64 `json:"coupon_id,omitempty"`
	// 优惠券类型；商品条件折扣券-1;商品满减券-2;商品统一折扣券-3;商品直减券-4;店铺条件折扣券-101;店铺满减券-102;店铺统一折扣券-103;店铺直减券-104
	Type int32 `json:"type,omitempty"`
	// 优惠券状态;未生效，编辑中-1;生效-2;已过期-3;已作废-4;删除-5;生效中-100;已过期-101;已经使用-102
	Status int32 `json:"status,omitempty"`
	// 优惠券创建时间
	CraeteTime string `json:"craete_time,omitempty"`
	// 优惠券更新时间
	UpdateTime string `json:"update_time,omitempty"`
	CouponInfo CouponCouponInfo `json:"coupon_info,omitempty"`
	StockInfo CouponStockInfo `json:"stock_info,omitempty"`
}
