/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// OrganizationCodeInfo 组织机构代码证信息
type OrganizationCodeInfo struct {
	// 1、请填写组织机构代码证上的组织机构代码。2、可填写9或10位 数字\\字母\\连字符。示例值;12345679-A
	OrganizationCode string `json:"organization_code"`
	// 注册日期，格式;2014-01-01
	StartDate string `json:"start_date"`
	// 结束有效期，格式;2014-01-01;1、若证件有效期为长期，请填写;长期。2、结束时间需大于开始时间。3、有效期必须大于60天，即结束时间距当前时间需超过60天。
	EndDate string `json:"end_date"`
	PicFile PicFile `json:"pic_file"`
}
