/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// FreightTemplateRsp 运费模版
type FreightTemplateRsp struct {
	// 模板ID
	TemplateId int64 `json:"template_id,omitempty"`
	// 计费类型,1-按件,2-按重量
	ValuationType int32 `json:"valuation_type,omitempty"`
	// 模板名称
	Name string `json:"name,omitempty"`
}
