/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SpuAddReqExpressInfo 运费信息
type SpuAddReqExpressInfo struct {
	// 运费模板ID（先通过获取运费模板接口delivery/get_freight_template拿到）
	TemplateId int64 `json:"template_id"`
}
