/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SpuAddRspData struct for SpuAddRspData
type SpuAddRspData struct {
	// 小商店内部商品ID
	ProductId int64 `json:"product_id,omitempty"`
	// 商家自定义商品ID
	OutProductId string `json:"out_product_id,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
