/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// DeliveryInfoDeliveryProductInfo struct for DeliveryInfoDeliveryProductInfo
type DeliveryInfoDeliveryProductInfo struct {
	// 快递单号
	WaybillId string `json:"waybill_id,omitempty"`
	// 快递公司编号
	DeliveryId string `json:"delivery_id,omitempty"`
}
