/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponInfoValidInfo 优惠券失效信息
type CouponInfoValidInfo struct {
	// 优惠券有效期结束时间，若填了start必填
	EndTime string `json:"end_time,omitempty"`
	// 优惠券有效期开始时间，和valid_day_num二选一
	StartTime int64 `json:"start_time,omitempty"`
	// 优惠券有效期天数，和start_time二选一
	ValidDayNum int64 `json:"valid_day_num"`
	// 优惠券有效期类型
	ValidType int64 `json:"valid_type"`
}
