/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// OrderOrderDetail 主图,多张,列表
type OrderOrderDetail struct {
	ProductInfos []PproductInfo `json:"product_infos,omitempty"`
	PayInfo PayInfo `json:"pay_info,omitempty"`
	PriceInfo PayInfo `json:"price_info,omitempty"`
}
