/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponCouponInfoValidInfo struct for CouponCouponInfoValidInfo
type CouponCouponInfoValidInfo struct {
	// 优惠券有效期类型
	ValidType string `json:"valid_type,omitempty"`
	// 优惠券有效天数，valid_type=2时才有意义
	ValidDayNum string `json:"valid_day_num,omitempty"`
	// 优惠券有效期开始时间，valid_type=1时才有意义
	StartTime string `json:"start_time,omitempty"`
	// 优惠券有效期结束时间，valid_type=1时才有意义
	EndTime string `json:"end_time,omitempty"`
}
