/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// StoreGetShopcatRsp 
type StoreGetShopcatRsp struct {
	// 系统异常为-1;token太长为-2
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	ShopcatList []ShopcatRsp `json:"shopcat_list,omitempty"`
}
