/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// PicFile 
type PicFile struct {
	// media_id，此处通过上传图片接口获得传入内容
	MediaId string `json:"media_id"`
	// media_id，此处通过上传图片接口获得传入内容
	PayMediaId string `json:"pay_media_id"`
}
