/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject21 struct for InlineObject21
type InlineObject21 struct {
	// 优惠券类型
	Type int32 `json:"type"`
	CouponInfo CouponInfo `json:"coupon_info"`
}
