/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// PriceInfo 
type PriceInfo struct {
	// 商品金额（单位：分）
	ProductPrice int64 `json:"product_price,omitempty"`
	// 订单金额（单位：分）
	OrderPrice int64 `json:"order_price,omitempty"`
	// 运费（单位：分）
	Freight int64 `json:"freight,omitempty"`
	// 优惠金额（单位：分）
	DiscountedPrice int64 `json:"discounted_price,omitempty"`
	// 是否有优惠（false：无优惠/true：有优惠）
	IsDiscounted bool `json:"is_discounted,omitempty"`
}
