/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	Appid string `json:"appid"`
	NameInfo NameInfo `json:"name_info"`
	ReturnInfo ReturnInfo `json:"return_info"`
}
