/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// StockGetRspData struct for StockGetRspData
type StockGetRspData struct {
	StockNum int64 `json:"stock_num,omitempty"`
}
