/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CheckAuditStatusRspData struct for CheckAuditStatusRspData
type CheckAuditStatusRspData struct {
	// 注册状态 0-成功 1-已发送协议还未签约 2-未发送协议或协议已过期，需发送协议，当register_status为0时以下字段有意义
	RegisterStatus int32 `json:"register_status,omitempty"`
	// 商家信息状态, 具体含义查看状态枚举值
	MerchantInfoStatus int32 `json:"merchant_info_status,omitempty"`
	// 账户验证状态, 具体含义查看状态枚举值
	AcctVerifyStatus int32 `json:"acct_verify_status,omitempty"`
	// 基础信息状态, 具体含义查看状态枚举值
	BasicInfoStatus int32 `json:"basic_info_status,omitempty"`
	// 支付签约状态, 具体含义查看状态枚举值
	PaySignStatus int32 `json:"pay_sign_status,omitempty"`
	// 基础信息驳回原因
	AuditRejectReasons string `json:"audit_reject_reasons,omitempty"`
	// 法人验证链接
	LegalValidationUrl string `json:"legal_validation_url,omitempty"`
	PayAuditDetail CheckAuditStatusRspDataPayAuditDetail `json:"pay_audit_detail,omitempty"`
	// 注册的appid
	RegisteredAppid string `json:"registered_appid,omitempty"`
}
