/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject22 struct for InlineObject22
type InlineObject22 struct {
	// 优惠券创建时间的搜索开始时间
	StartCreateTime string `json:"start_create_time"`
	// 优惠券创建时间的搜索结束时间
	EndCreateTime string `json:"end_create_time"`
	// 优惠券状态
	Status int32 `json:"status"`
	// 第几页（最小填1）
	Page int32 `json:"page"`
	// 每页数量(不超过10,000)
	PageSize int32 `json:"page_size"`
}
