/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// AfterSaleInfo 
type AfterSaleInfo struct {
	// 正在售后流程的售后单数
	OnAftersaleOrderCnt int64 `json:"on_aftersale_order_cnt,omitempty"`
	// 售后单ID列表
	AftersaleOrderList []AfterSaleInfoAftersaleOrderList `json:"aftersale_order_list,omitempty"`
}
