/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SkuAddRspData struct for SkuAddRspData
type SkuAddRspData struct {
	// skuID
	SkuId int64 `json:"sku_id,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
