/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CheckAuditStatusRsp 
type CheckAuditStatusRsp struct {
	// 系统异常--1;token太长--2;参数有误-9401020;无权限调用该api-9401021
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	Data CheckAuditStatusRspData `json:"data,omitempty"`
}
