/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponInfoExtInfo 优惠券失效信息
type CouponInfoExtInfo struct {
	// 优惠券失效时间
	InvalidTime string `json:"invalid_time"`
	// 商品折扣券领取后跳转的商品id
	JumpProductId int64 `json:"jump_product_id,omitempty"`
	// 备注信息
	Notes string `json:"notes,omitempty"`
	// 优惠券有效时间
	ValidTime string `json:"valid_time"`
}
