/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponInfoPromoteInfo 优惠券失效信息
type CouponInfoPromoteInfo struct {
	// 用户自定义推广渠道
	CustomizeChannel string `json:"customize_channel"`
	// 推广类型
	PromoteType string `json:"promote_type"`
}
