/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// ShopcatRsp 运费模版
type ShopcatRsp struct {
	// 分类ID
	ShopcatId int64 `json:"shopcat_id,omitempty"`
	// 父分类ID
	FShopcatId int64 `json:"f_shopcat_id,omitempty"`
	// 分类层级
	CatLevel int64 `json:"cat_level,omitempty"`
	// 分类名称
	ShopcatName string `json:"shopcat_name,omitempty"`
}
