/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// SkuBatchAddRsp 
type SkuBatchAddRsp struct {
	// 系统异常--1;token太长--2;参数有误-9401020;SkU不存在-9401006;SkU已经存在-9401005;SkU不允许编辑-9401025
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
	Data SkuAddRspData `json:"data,omitempty"`
}
