/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// BrandRsp 品牌详情
type BrandRsp struct {
	// 第一级类目
	FirstCatId int64 `json:"first_cat_id,omitempty"`
	// 第二级类目
	SecondCatId int64 `json:"second_cat_id,omitempty"`
	// 第三级类目
	ThirdCatId int64 `json:"third_cat_id,omitempty"`
	BrandInfo BrandRspBrandInfo `json:"brand_info,omitempty"`
}
