/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// AddressInfo 
type AddressInfo struct {
	// 收货人姓名
	UserName string `json:"user_name"`
	// 邮编
	PostalCode int32 `json:"postal_code,omitempty"`
	// 国标收货地址第一级地址
	ProvinceName string `json:"province_name"`
	// 国标收货地址第二级地址
	CityName string `json:"city_name"`
	// 国标收货地址第三级地址
	CountyName string `json:"county_name"`
	// 详细收货地址信息
	DetailInfo string `json:"detail_info,omitempty"`
	// 收货地址国家码
	NationalCode int32 `json:"national_code,omitempty"`
	// 收货人手机号码
	TelNumber string `json:"tel_number"`
}
