/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject18 struct for InlineObject18
type InlineObject18 struct {
	// 订单ID，可从获取订单列表中获得
	OrderId int64 `json:"order_id"`
}
