/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject8 struct for InlineObject8
type InlineObject8 struct {
	Keyword string `json:"keyword"`
	// 第几页（最小填1）
	Page int32 `json:"page"`
	// 每页数量(不超过10,000)
	PageSize int32 `json:"page_size"`
}
