/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject19 struct for InlineObject19
type InlineObject19 struct {
	// 订单支付时间的搜索开始时间
	StartPayTime string `json:"start_pay_time,omitempty"`
	// 订单支付时间的搜索结束时间
	EndPayTime string `json:"end_pay_time,omitempty"`
	// 商品标题关键词
	Title string `json:"title,omitempty"`
	// 商品编码
	SkuCode string `json:"sku_code,omitempty"`
	// 收件人
	UserName string `json:"user_name,omitempty"`
	// 收件人电话
	TelNumber string `json:"tel_number,omitempty"`
	// 不填该参数:全部订单 0:没有正在售后的订单, 1:正在售后单数量大于等于1的订单
	OnAftersaleOrderExist int32 `json:"on_aftersale_order_exist,omitempty"`
	// 订单状态
	Status int32 `json:"status,omitempty"`
	// 第几页（最小填1）
	Page int32 `json:"page"`
	// 每页数量(不超过10,000)
	PageSize int32 `json:"page_size"`
}
