/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// InlineObject13 struct for InlineObject13
type InlineObject13 struct {
	// 商品状态
	ProductId int64 `json:"product_id"`
	// 默认0:获取线上数据, 1:获取草稿数据
	NeedEditSku int32 `json:"need_edit_sku,omitempty"`
	// 默认0:获取草稿库存, 1:获取线上真实库存
	NeedRealStock int32 `json:"need_real_stock,omitempty"`
}
