/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// AfterSaleInfoAftersaleOrderList struct for AfterSaleInfoAftersaleOrderList
type AfterSaleInfoAftersaleOrderList struct {
	AftersaleOrderId int64 `json:"aftersale_order_id,omitempty"`
}
