/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// DeliverySendRsp 
type DeliverySendRsp struct {
	// 系统异常--1;token太长--2;参数有误-9401020;无权限调用该api-9401021;订单在售后中,不允许发货&确认收货-108009;发货失败-109000;已经发货-109001
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
}
