/*
 * 微信小商店开放API
 *
 * wei xin xiao shang dian open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wxxiaodian
// CouponInfoDiscountInfo 折扣信息
type CouponInfoDiscountInfo struct {
	DiscountCondition CouponInfoDiscountInfoDiscountCondition `json:"discount_condition,omitempty"`
	// 满减金额
	DiscountFee int64 `json:"discount_fee"`
	// 打折商品数量，满减券需填写
	DiscountNum int64 `json:"discount_num,omitempty"`
}
